<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('nationalities')->insert([
            ['country_name' => 'El Salvador', 'country_code' => '+503'],
            ['country_name' => 'Estados Unidos', 'country_code' => '+1'],
            ['country_name' => 'Canadá', 'country_code' => '+1'],
            ['country_name' => 'México', 'country_code' => '+52'],
            ['country_name' => 'Guatemala', 'country_code' => '+502'],
            ['country_name' => 'Honduras', 'country_code' => '+504'],
            ['country_name' => 'Nicaragua', 'country_code' => '+505'],
            ['country_name' => 'Costa Rica', 'country_code' => '+506'],
            ['country_name' => 'Panamá', 'country_code' => '+507'],
            ['country_name' => 'Colombia', 'country_code' => '+57'],
            ['country_name' => 'Argentina', 'country_code' => '+54'],
            ['country_name' => 'Chile', 'country_code' => '+56'],
            ['country_name' => 'España', 'country_code' => '+34'],
            ['country_name' => 'Reino Unido', 'country_code' => '+44'],
            ['country_name' => 'Alemania', 'country_code' => '+49'],
            ['country_name' => 'Francia', 'country_code' => '+33'],
            ['country_name' => 'Italia', 'country_code' => '+39'],
            ['country_name' => 'Brasil', 'country_code' => '+55'],
            ['country_name' => 'Perú', 'country_code' => '+51'],
            ['country_name' => 'Ecuador', 'country_code' => '+593'],
            ['country_name' => 'Uruguay', 'country_code' => '+598'],
            ['country_name' => 'Paraguay', 'country_code' => '+595'],
            ['country_name' => 'Venezuela', 'country_code' => '+58'],
            ['country_name' => 'Bolivia', 'country_code' => '+591'],
            ['country_name' => 'República Dominicana', 'country_code' => '+1'],
            ['country_name' => 'Cuba', 'country_code' => '+53'],
            ['country_name' => 'Puerto Rico', 'country_code' => '+1'],
            ['country_name' => 'Jamaica', 'country_code' => '+1876'],
            ['country_name' => 'Rusia', 'country_code' => '+7'],
            ['country_name' => 'China', 'country_code' => '+86'],
            ['country_name' => 'Japón', 'country_code' => '+81'],
            ['country_name' => 'India', 'country_code' => '+91'],
            ['country_name' => 'Pakistán', 'country_code' => '+92'],
            ['country_name' => 'Filipinas', 'country_code' => '+63'],
            ['country_name' => 'Corea del Sur', 'country_code' => '+82'],
            ['country_name' => 'Indonesia', 'country_code' => '+62'],
            ['country_name' => 'Malasia', 'country_code' => '+60'],
            ['country_name' => 'Vietnam', 'country_code' => '+84'],
            ['country_name' => 'Tailandia', 'country_code' => '+66'],
            ['country_name' => 'Australia', 'country_code' => '+61'],
            ['country_name' => 'Nueva Zelanda', 'country_code' => '+64'],
            ['country_name' => 'Egipto', 'country_code' => '+20'],
            ['country_name' => 'Sudáfrica', 'country_code' => '+27'],
            ['country_name' => 'Nigeria', 'country_code' => '+234'],
            ['country_name' => 'Kenia', 'country_code' => '+254'],
            ['country_name' => 'Ghana', 'country_code' => '+233'],
            ['country_name' => 'Argelia', 'country_code' => '+213'],
            ['country_name' => 'Marruecos', 'country_code' => '+212'],
            ['country_name' => 'Túnez', 'country_code' => '+216'],
            ['country_name' => 'Israel', 'country_code' => '+972'],
            ['country_name' => 'Arabia Saudita', 'country_code' => '+966'],
            ['country_name' => 'Emiratos Árabes Unidos', 'country_code' => '+971'],
            ['country_name' => 'Irak', 'country_code' => '+964'],
            ['country_name' => 'Irán', 'country_code' => '+98'],
            ['country_name' => 'Turquía', 'country_code' => '+90'],
            ['country_name' => 'Qatar', 'country_code' => '+974'],
            ['country_name' => 'Kuwait', 'country_code' => '+965'],
            ['country_name' => 'Jordania', 'country_code' => '+962'],
            ['country_name' => 'Líbano', 'country_code' => '+961'],
            ['country_name' => 'Siria', 'country_code' => '+963'],
            ['country_name' => 'Grecia', 'country_code' => '+30'],
            ['country_name' => 'Portugal', 'country_code' => '+351'],
            ['country_name' => 'Irlanda', 'country_code' => '+353'],
            ['country_name' => 'Suecia', 'country_code' => '+46'],
            ['country_name' => 'Noruega', 'country_code' => '+47'],
            ['country_name' => 'Finlandia', 'country_code' => '+358'],
            ['country_name' => 'Polonia', 'country_code' => '+48'],
            ['country_name' => 'Países Bajos', 'country_code' => '+31'],
            ['country_name' => 'Bélgica', 'country_code' => '+32'],
            ['country_name' => 'Suiza', 'country_code' => '+41'],
            ['country_name' => 'Austria', 'country_code' => '+43'],
            ['country_name' => 'Dinamarca', 'country_code' => '+45'],
            ['country_name' => 'Chequia', 'country_code' => '+420'],
            ['country_name' => 'Hungría', 'country_code' => '+36'],
            ['country_name' => 'Rumanía', 'country_code' => '+40'],
            ['country_name' => 'Bulgaria', 'country_code' => '+359'],
        ]);
    }
}